config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admins
  resources :companies do
    resources :metrics  
  end
  resources :metrics
  resources :deals
  root 'home#index'

  get 'parts/navigation'

  get 'parts/footer'

end

app/models/metric.rb
class Metric < ActiveRecord::Base
    belongs_to :company
    
    belongs_to :metric_list
    belongs_to :period_type
    
    has_many :metric_values, :dependent => :destroy
    accepts_nested_attributes_for :metric_values,  :reject_if => :all_blank, :allow_destroy => true
end

app/controllers/metrics_controller.rb
class MetricsController < ApplicationController
  before_action :set_metric, only: [:show, :edit, :update, :destroy]
  layout "dashboard"

  # GET /metrics
  # GET /metrics.json
  def index
    @metrics = Metric.all
  end

  # GET /metrics/1
  # GET /metrics/1.json
  def show
  end

  # GET /metrics/new
  def new
    @company = Company.find(params[:company_id])
    @metric = @company.metrics.build
    @metric_value = @metric.metric_values.build 
  end

  # GET /metrics/1/edit
  def edit
    @company = Company.find(params[:company_id])
    @metric = @company.metrics.find(params[:id])
  end

  # POST /metrics
  # POST /metrics.json
  def create
    @metric = Metric.new(metric_params)
    respond_to do |format|
      if @metric.save
        format.html { redirect_to company_metric_path(@metric.company_id ,@metric, :ml_id => @metric.metric_list_id), notice: 'Metric was successfully created.' }
        format.json { render :show, status: :created, location: [@company,@metric] }
      else
        format.html { render :new }
        format.json { render json: @metric.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /metrics/1
  # PATCH/PUT /metrics/1.json
  def update
    respond_to do |format|
      if @metric.update(metric_params)
        format.html { redirect_to company_metric_path(@metric.company_id ,@metric, :ml_id => @metric.metric_list_id), notice: 'Metric was successfully updated.' }
        format.json { render :show, status: :ok, location: @metric }
      else
        format.html { render :edit }
        format.json { render json: @metric.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /metrics/1
  # DELETE /metrics/1.json
  def destroy
    @metric.destroy
    respond_to do |format|
      format.html { redirect_to metrics_url, notice: 'Metric was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_metric
      @metric = Metric.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def metric_params
      params.require(:metric).permit(:company_id, :period_type_id, :metric_list_id, metric_values_attributes: [:id, :period_value_id, :year,:value,:_destroy])
    end
end

app/helpers/metrics_helper.rb
module MetricsHelper
end

app/views/metrics/_form.html.erb
<%= form_for [@company,@metric], :html => { :class => "form-horizontal metric" } do |f| %>

  <% if @metric.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@metric.errors.count, "error") %> prohibited this metric from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @metric.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>
  <div class="panel-group">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" href="#collapse1">
          <% if @metric.metric_list.try(:name).present? %> 
          <%= @metric.metric_list.try(:name) %> 
          <% else %>
            new metric
          <% end %>
          </a>
      </h4>
    </div>
    <div id="collapse1" class="panel-collapse collapse in">
      <div class="panel-body">
         <div class="form-group">
          <%= f.label :company_id, :class => 'control-label col-lg-2' %>
          <div class="col-lg-10">
            <%= f.text_field :company_id, :class => 'form-control', :value => params[:company_id] %>
          </div>
          <%=f.error_span(:company_id) %>
        </div>
        <div class="form-group">
          <%= f.label :period_type_id, :class => 'control-label col-lg-2' %>
          <div class="col-lg-10">
                  <%= f.collection_select :period_type_id, PeriodType.order(:name),:id,:name, class: 'form-control' %>
          </div>
          <%=f.error_span(:period_type_id) %>
        </div>
        <div class="form-group" display="none">
          <%= f.label :metric_list_id, :class => 'control-label col-lg-2' %>
          <div class="col-lg-10">
            <%= f.text_field :metric_list_id, :class => 'form-control', :value => params[:ml_id] %>
          </div>
          <%=f.error_span(:metric_list_id) %>
        </div>
      </div>
      <div class="panel-body">
            <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal">Open Modal</button>
              <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog modal-bg">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Metric List</h4>
        </div>
        <div class="modal-body">

      <table class="table table-hover" id="mtable">
        <tbody class="metric_values">
        <%= f.fields_for :metric_values do |builder| %>
            <%= render 'metric_value_fields', f: builder %>
        <% end %>
        </tbody>
        </table>
        <div class='links' id="clickini">
        <%= link_to_add_association '+', f, :metric_values, :data => {"association-insertion-node" => "tbody.metric_values", "association-insertion-method" => "append"} ,:class => 'btn btn-success' %>
      </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
</div>

      </div>
      <div class="panel-footer">
          <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-success btn-block' %>
    </div>
  </div>
      </div>
    </div>
  </div>
</div>
<script>
//   $(document).keypress(function(e) {
//     if(e.which == 13) {
// $('.metric').submit(function() {
//   return false;
// });});

// $( document ).ready(function() {
//   $(document).keypress(function(e) {
//     if(e.which == 13) {
//         $( ".add_fields" ).click();
//     }
// });
// });
</script>

<% end %>

app/views/metrics/_metric_value_fields.html.erb
<tr class="nested-fields">
<td>      <%= f.collection_select :period_value_id, PeriodValue.where("period_type_id = ?", @metric.period_type_id).order(:name), :id, :name, {}, {class: "form-control"} %></td>
  <td><%= f.text_field :year,:placeholder =>'Year', :class => 'form-control' %></td>
  <td><%= f.text_field :value,:placeholder =>'value',:class => 'form-control' %></td>    
</tr>

app/views/metrics/edit.html.erb
<%- model_class = Metric -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/metrics/index.html.erb
<div class="col-md-12">
  <div class="content-panel">
    <div class="panel-body">
    <%- model_class = Metric -%>
    <h4>List of generated metrics</h4>
    <hr>
    <table class="table table-striped">
      <thead>
        <tr>
          <th><%= model_class.human_attribute_name(:id) %></th>
          <th><%= model_class.human_attribute_name(:period_type_id) %></th>
          <th><%= model_class.human_attribute_name(:metric_list_id) %></th>
          <th><%=t '.actions', :default => t("helpers.actions") %></th>
        </tr>
      </thead>
      <tbody>
        <% @metrics.each do |metric| %>
          <tr>
            <td><%= link_to metric.company.name, metric_path(metric), :class => 'btn btn-theme btn-xs' %></td>
            <td><%= metric.period_type.name %></td>
            <td><%= metric.metric_list.name %></td>
            <td>
              <%= link_to t('.edit', :default => t("helpers.links.edit")),
                          edit_metric_path(metric), :class => 'btn btn-default btn-xs' %>
              <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                          metric_path(metric),
                          :method => :delete,
                          :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                          :class => 'btn btn-xs btn-danger' %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= link_to t('.new', :default => t("helpers.links.new")),
                new_metric_path,
                :class => 'btn btn-primary' %>

    </div>
  </div>
  
</div>

app/views/metrics/new.html.erb
<%- model_class = Metric -%>
<div class="page-header">
  <h1>Metric Setting</h1>
</div>
<%= render :partial => 'form' %>

app/views/metrics/show.html.erb
<%- model_class = Metric -%>
  <h4><%=t '.title', :default => model_class.model_name.human.titleize %></h4>
  <hr>
<div class="container">
<div class="col-md-6">
  <div class="content-panel">
    <div class="panel-body">
      <dl class="dl-horizontal">
    <dt><strong><%= model_class.human_attribute_name(:company_id) %>:</strong></dt>
    <dd><%= @metric.company.name %></dd>
    <dt><strong><%= model_class.human_attribute_name(:period_type_id) %>:</strong></dt>
    <dd><%= @metric.period_type.name %></dd>
    <dt><strong><%= model_class.human_attribute_name(:metric_list_id) %>:</strong></dt>
    <dd><%= @metric.metric_list.name %></dd>
  </dl>      
    </div>
  </div>
</div>

    <div class="col-md-6">
      <div class="content-panel"> 
        <div class="panel-body text-center">
          <button id="changeToBar">Bar</button>
          <button id="changeToLine">Line</button>
          <button id="changeToRadar">Radar</button>
          <button id="changeToPolarArea">Polar Area</button>
          <button id="changeToPie">Pie</button>
          <button id="changeToDoughnut">Doughnut</button>
          <canvas id="myChart" ></canvas> 
        </div>
      </div>
    </div>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_company_metric_path(  @metric.company_id ,@metric, :ml_id => @metric.metric_list_id), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              company_metric_path(@metric.company_id, @metric),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

</div>

<script>
var chartData = {
  labels: [<% @metric.metric_values.each do |mvc|%> "<%= mvc.period_value.name.to_s %>",<% end %>],
  datasets: [{
    label: '# <%= @metric.metric_list.name %>',
    data: [<% @metric.metric_values.each do |mvc|%> <%= mvc.value %>,<% end %>],
                backgroundColor: [
                'rgba(255, 99, 132, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(255, 206, 86, 0.2)',
                'rgba(75, 192, 192, 0.2)',
                'rgba(153, 102, 255, 0.2)',
                'rgba(255, 159, 64, 0.2)'
            ],
            borderColor: [
                'rgba(255,99,132,1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(255, 159, 64, 1)'
            ],
            borderWidth: 1
  }]
};
var ctx = document.getElementById("myChart");
var myChart = new Chart(ctx, {
  type: 'bar',
  data: chartData
});

document.getElementById('changeToLine').onclick = function() {
  myChart.destroy();
  myChart = new Chart(ctx, {
    type: 'line',
    data: chartData
  });
};

document.getElementById('changeToBar').onclick = function() {
  myChart.destroy();
  myChart = new Chart(ctx, {
    type: 'bar',
    data: chartData
  });
};

document.getElementById('changeToRadar').onclick = function() {
  myChart.destroy();
  myChart = new Chart(ctx, {
    type: 'radar',
    data: chartData
  });
};
document.getElementById('changeToPolarArea').onclick = function() {
  myChart.destroy();
  myChart = new Chart(ctx, {
    type: 'polarArea',
    data: chartData
  });
};
document.getElementById('changeToPie').onclick = function() {
  myChart.destroy();
  myChart = new Chart(ctx, {
    type: 'pie',
    data: chartData
  });
};
document.getElementById('changeToDoughnut').onclick = function() {
  myChart.destroy();
  myChart = new Chart(ctx, {
    type: 'doughnut',
    data: chartData
  });
};



</script>