config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admins
  resources :companies do
    resources :metrics  
  end
  resources :metrics
  resources :deals
  root 'home#index'

  get 'parts/navigation'

  get 'parts/footer'

end

app/models/company.rb
class Company < ActiveRecord::Base
    has_many :founders, :dependent => :destroy
    accepts_nested_attributes_for :founders,  :reject_if => :all_blank, :allow_destroy => true
    has_many :coverages, :dependent => :destroy
    accepts_nested_attributes_for :coverages,  :reject_if => :all_blank, :allow_destroy => true
    has_many :metrics
    has_many :metric_lists
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]
  layout "dashboard"

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    @mc = MetricCategory.all
  end

  # GET /companies/new
  def new
    @company = Company.new
    @company.founders.build
    @company.coverages.build
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :registration_name, :headquater, :country, :founded, :link, :business_model, :industry, :consumer_target, :latest_financial, :total_fund_raised,founders_attributes:[:id,:name,:position,:linkedin,:description])
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_coverage_fields.html.erb
        <div class="form-group">
        <%= f.label :title, :class => 'control-label col-lg-2' %>
          <div class="col-lg-10">
          <%= f.text_field :title, :class => 'form-control' %>
          </div>
        <%=f.error_span(:title) %>
      </div>
      <div class="form-group">
        <%= f.label :date, :class => 'control-label col-lg-2' %>
          <div class="col-lg-10">
          <%= f.text_field :date, :class => 'form-control' %>
          </div>
        <%=f.error_span(:date) %>
      </div>
            <div class="form-group">
        <%= f.label :link, :class => 'control-label col-lg-2' %>
          <div class="col-lg-10">
          <%= f.text_field :link, :class => 'form-control' %>
          </div>
        <%=f.error_span(:link) %>
      </div>

app/views/companies/_form.html.erb
<%= form_for @company, :html => { :class => "form-horizontal company" } do |f| %>

  <% if @company.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @company.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>
  
<ul class="nav nav-tabs">
  <li class="active"><a data-toggle="tab" href="#company">Company</a></li>
  <li><a data-toggle="tab" href="#founder">Founder</a></li>
  <li><a data-toggle="tab" href="#media">Media</a></li>
  <li><a data-toggle="tab" href="#finance">Finance</a></li>
</ul>

<div class="tab-content">
  
<div id="company" class="tab-pane fade in active">
  <br>
  <div class="row">
  <div class="col-md-3">
    <h3>Company</h3>
  </div>
    <div class="col-md-9">
  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :registration_name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :registration_name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:registration_name) %>
  </div>
  <div class="form-group">
    <%= f.label :headquater, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :headquater, :class => 'form-control' %>
    </div>
    <%=f.error_span(:headquater) %>
  </div>
  <div class="form-group">
    <%= f.label :country, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :country, :class => 'form-control' %>
    </div>
    <%=f.error_span(:country) %>
  </div>
  <div class="form-group">
    <%= f.label :founded, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :founded, :class => 'form-control' %>
    </div>
    <%=f.error_span(:founded) %>
  </div>
  <div class="form-group">
    <%= f.label :link, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :link, :class => 'form-control' %>
    </div>
    <%=f.error_span(:link) %>
  </div>
  <div class="form-group">
    <%= f.label :business_model, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :business_model, :class => 'form-control' %>
    </div>
    <%=f.error_span(:business_model) %>
  </div>
  <div class="form-group">
    <%= f.label :industry, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :industry, :class => 'form-control' %>
    </div>
    <%=f.error_span(:industry) %>
  </div>
  <div class="form-group">
    <%= f.label :consumer_target, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :consumer_target, :class => 'form-control' %>
    </div>
    <%=f.error_span(:consumer_target) %>
  </div>
  </div>
</div>
</div>
  
<div id="founder" class="tab-pane fade">
  <br>
  <div class="row">
    <div class="col-md-3">
    <h3>Founder</h3>
    </div>
    <div class="col-md-9">
      <div class="line_items">
        <%= f.fields_for :founders do |builder|  %>
          <%= render 'founder_fields', f: builder %>
        <% end %>
        </div>
    </div>
  </div>
</div>

<div id="media" class="tab-pane fade">
  <br>
  <div class="row">
    <div class="col-md-3">
      <h3>Media Coverage</h3>
    </div>
    <div class="col-md-9">
        <%= f.fields_for :coverages do |builder|  %>
        <% end %>
    </div>
  </div>
</div>
  


<div id="finance" class="tab-pane fade">
  <br>
  <div class="row">
    <div class="col-md-3">
        <h3>Financial</h3>
    </div>
    <div class="col-md-9">
      <div class="form-group">
        <%= f.label :latest_financial, :class => 'control-label col-lg-2' %>
        <div class="col-lg-10">
          <%= f.text_field :latest_financial, :class => 'form-control' %>
        </div>
        <%=f.error_span(:latest_financial) %>
      </div>
      <div class="form-group">
        <%= f.label :total_fund_raised, :class => 'control-label col-lg-2' %>
        <div class="col-lg-10">
          <%= f.text_field :total_fund_raised, :class => 'form-control' %>
        </div>
        <%=f.error_span(:total_fund_raised) %>
      </div>
    </div>
  </div>
</div>
  
</div>
  
  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-success' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                companies_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/companies/_founder_fields.html.erb
        <div class="form-group">
        <%= f.label :name, :class => 'control-label col-lg-2' %>
          <div class="col-lg-10">
          <%= f.text_field :name, :class => 'form-control' %>
          </div>
        <%=f.error_span(:name) %>
      </div>
      <div class="form-group">
        <%= f.label :position, :class => 'control-label col-lg-2' %>
          <div class="col-lg-10">
          <%= f.text_field :position, :class => 'form-control' %>
          </div>
        <%=f.error_span(:position) %>
      </div>
            <div class="form-group">
        <%= f.label :linkedin, :class => 'control-label col-lg-2' %>
          <div class="col-lg-10">
          <%= f.text_field :linkedin, :class => 'form-control' %>
          </div>
        <%=f.error_span(:linkedin) %>
      </div>
            <div class="form-group">
        <%= f.label :description, :class => 'control-label col-lg-2' %>
          <div class="col-lg-10">
          <%= f.text_area :description, :class => 'form-control' %>
          </div>
        <%=f.error_span(:description) %>
      </div>

app/views/companies/edit.html.erb
<%- model_class = Company -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/companies/index.html.erb
<div class="col-md-12">
  <div class="content-panel">
    <div class="panel-body">
      <h4>Companies</h4>
      <hr>
      <%- model_class = Company -%>
      <table class="table table-striped table-advance table-hover">
        <thead>
          <tr>
            <th><%= model_class.human_attribute_name(:name) %></th>
            <th><%= model_class.human_attribute_name(:registration_name) %></th>
            <th><%= model_class.human_attribute_name(:country) %></th>
            <th><%= model_class.human_attribute_name(:founded) %></th>
            <th><%= model_class.human_attribute_name(:link) %></th>
            <th><%= model_class.human_attribute_name(:business_model) %></th>
            <th><%= model_class.human_attribute_name(:industry) %></th>
            <th><%= model_class.human_attribute_name(:consumer_target) %></th>
            <th><%= model_class.human_attribute_name(:latest_financial) %></th>
            <th><%= model_class.human_attribute_name(:total_fund_raised) %></th>
            <th><%=t '.actions', :default => t("helpers.actions") %></th>
          </tr>
        </thead>
        <tbody>
          <% @companies.each do |company| %>
            <tr>
              <td><%= link_to company.name,company_path(company)  %></td>
              <td><%= company.registration_name %></td>
              <td><%= company.country %></td>
              <td><%= company.founded %></td>
              <td><%= company.link %></td>
              <td><%= company.business_model %></td>
              <td><%= company.industry %></td>
              <td><%= company.consumer_target %></td>
              <td><%= company.latest_financial %></td>
              <td><%= company.total_fund_raised %></td>
              <td>
                <%= link_to t('.edit', :default => t("helpers.links.edit")),
                            edit_company_path(company), :class => 'btn btn-default btn-xs' %>
                <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                            company_path(company),
                            :method => :delete,
                            :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                            :class => 'btn btn-xs btn-danger' %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      
      <%= link_to t('.new', :default => t("helpers.links.new")),
                  new_company_path,
                  :class => 'btn btn-primary' %>

      
    </div>
  </div>
  
</div>

app/views/companies/new.html.erb
<div class="col-md-12">
    <div class="content-panel">
        <div class="panel-body">
            <%- model_class = Company -%>
              <h4><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h4>
            <hr>
            <%= render :partial => 'form' %>
            
        </div>
    </div>
</div>

app/views/companies/show.html.erb
<div class="col-md-12">
  <div class="content-panel">
    <div class="panel-body">
      <%- model_class = Company -%>
      <h4><%=t '.title', :default => model_class.model_name.human.titleize %></h4>
      <hr>
      <dl class="dl-horizontal">
        <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
        <dd><%= @company.name %></dd>
        <dt><strong><%= model_class.human_attribute_name(:registration_name) %>:</strong></dt>
        <dd><%= @company.registration_name %></dd>
        <dt><strong><%= model_class.human_attribute_name(:headquater) %>:</strong></dt>
        <dd><%= @company.headquater %></dd>
        <dt><strong><%= model_class.human_attribute_name(:country) %>:</strong></dt>
        <dd><%= @company.country %></dd>
        <dt><strong><%= model_class.human_attribute_name(:founded) %>:</strong></dt>
        <dd><%= @company.founded %></dd>
        <dt><strong><%= model_class.human_attribute_name(:link) %>:</strong></dt>
        <dd><%= @company.link %></dd>
        <dt><strong><%= model_class.human_attribute_name(:business_model) %>:</strong></dt>
        <dd><%= @company.business_model %></dd>
        <dt><strong><%= model_class.human_attribute_name(:industry) %>:</strong></dt>
        <dd><%= @company.industry %></dd>
        <dt><strong><%= model_class.human_attribute_name(:consumer_target) %>:</strong></dt>
        <dd><%= @company.consumer_target %></dd>
        <dt><strong><%= model_class.human_attribute_name(:latest_financial) %>:</strong></dt>
        <dd><%= @company.latest_financial %></dd>
        <dt><strong><%= model_class.human_attribute_name(:total_fund_raised) %>:</strong></dt>
        <dd><%= @company.total_fund_raised %></dd>
      </dl>
      
      <%= link_to t('.back', :default => t("helpers.links.back")),
                    companies_path, :class => 'btn btn-default'  %>
      <%= link_to t('.edit', :default => t("helpers.links.edit")),
                    edit_company_path(@company), :class => 'btn btn-default' %>
      <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                    company_path(@company),
                    :method => 'delete',
                    :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                    :class => 'btn btn-danger' %>
      <div class="container">
        <h2>list metrics</h2>
        <% @company.metrics.each do  |cmd| %>
            <p><%=  cmd.metric_list.name %> <%= link_to 'show', company_metric_path(:id => cmd.id, :ml_id =>cmd.metric_list_id, :company_id => @company) %> </p>
        <% end %>
        
      </div>
      <div class="container">
      <h2>Create Metrics</h2>
      <% @mc.each do |mc| %>
      <div class="panel-group">
        <div class="panel-default">
          <div class="panel-heading">
            <h4 class="panel-title">
              <a data-toggle="collapse" href="#collapse<%= mc.id %>"><%= mc.name %></a>
            </h4>
          </div>
          <div id="collapse1" class="panel-collapse collapse">
            <ul class="list-group">
                <% mc.metric_lists.each do |ml| %>
              <li class="list-group-item"><%= ml.name %>  <%= link_to 'create', new_company_metric_path(:ml_id => ml.id, :company_id => params[:id]) %></li>
                  <% end %>
            </ul>
          </div>
        </div>
      </div>
      <% end %>
      </div>
    </div>
  </div>
  
</div>