config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admins
  resources :companies do
    resources :metrics  
  end
  resources :metrics
  resources :deals
  root 'home#index'

  get 'parts/navigation'

  get 'parts/footer'

end

app/models/deal.rb
class Deal < ActiveRecord::Base
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
  before_action :set_deal, only: [:show, :edit, :update, :destroy]
  layout "dashboard"

  # GET /deals
  # GET /deals.json
  def index
    @deals = Deal.all
  end

  # GET /deals/1
  # GET /deals/1.json
  def show
  end

  # GET /deals/new
  def new
    @deal = Deal.new
  end

  # GET /deals/1/edit
  def edit
  end

  # POST /deals
  # POST /deals.json
  def create
    @deal = Deal.new(deal_params)

    respond_to do |format|
      if @deal.save
        format.html { redirect_to @deal, notice: 'Deal was successfully created.' }
        format.json { render :show, status: :created, location: @deal }
      else
        format.html { render :new }
        format.json { render json: @deal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /deals/1
  # PATCH/PUT /deals/1.json
  def update
    respond_to do |format|
      if @deal.update(deal_params)
        format.html { redirect_to @deal, notice: 'Deal was successfully updated.' }
        format.json { render :show, status: :ok, location: @deal }
      else
        format.html { render :edit }
        format.json { render json: @deal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /deals/1
  # DELETE /deals/1.json
  def destroy
    @deal.destroy
    respond_to do |format|
      format.html { redirect_to deals_url, notice: 'Deal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_deal
      @deal = Deal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def deal_params
      params.require(:deal).permit(:company, :capital, :type, :round, :closing, :admin)
    end
end

app/helpers/deals_helper.rb
module DealsHelper
end

app/views/deals/_form.html.erb
<%= form_for @deal, :html => { :class => "form-horizontal deal" } do |f| %>

  <% if @deal.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@deal.errors.count, "error") %> prohibited this deal from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @deal.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :company, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :company, :class => 'form-control' %>
    </div>
    <%=f.error_span(:company) %>
  </div>
  <div class="form-group">
    <%= f.label :capital, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :capital, :class => 'form-control' %>
    </div>
    <%=f.error_span(:capital) %>
  </div>
  <div class="form-group">
    <%= f.label :type, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :type, :class => 'form-control' %>
    </div>
    <%=f.error_span(:type) %>
  </div>
  <div class="form-group">
    <%= f.label :round, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :round, :class => 'form-control' %>
    </div>
    <%=f.error_span(:round) %>
  </div>
  <div class="form-group">
    <%= f.label :closing, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :closing, :class => 'form-control' %>
    </div>
    <%=f.error_span(:closing) %>
  </div>
  <div class="form-group">
    <%= f.label :admin, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :admin, :class => 'form-control' %>
    </div>
    <%=f.error_span(:admin) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                deals_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/deals/edit.html.erb
<%- model_class = Deal -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/deals/index.html.erb
<%- model_class = Deal -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:company) %></th>
      <th><%= model_class.human_attribute_name(:capital) %></th>
      <th><%= model_class.human_attribute_name(:type) %></th>
      <th><%= model_class.human_attribute_name(:round) %></th>
      <th><%= model_class.human_attribute_name(:closing) %></th>
      <th><%= model_class.human_attribute_name(:admin) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @deals.each do |deal| %>
      <tr>
        <td><%= link_to deal.id, deal_path(deal) %></td>
        <td><%= deal.company %></td>
        <td><%= deal.capital %></td>
        <td><%= deal.type %></td>
        <td><%= deal.round %></td>
        <td><%= deal.closing %></td>
        <td><%= deal.admin %></td>
        <td><%=l deal.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_deal_path(deal), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      deal_path(deal),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_deal_path,
            :class => 'btn btn-primary' %>

app/views/deals/new.html.erb
<%- model_class = Deal -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/deals/show.html.erb
<%- model_class = Deal -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:company) %>:</strong></dt>
  <dd><%= @deal.company %></dd>
  <dt><strong><%= model_class.human_attribute_name(:capital) %>:</strong></dt>
  <dd><%= @deal.capital %></dd>
  <dt><strong><%= model_class.human_attribute_name(:type) %>:</strong></dt>
  <dd><%= @deal.type %></dd>
  <dt><strong><%= model_class.human_attribute_name(:round) %>:</strong></dt>
  <dd><%= @deal.round %></dd>
  <dt><strong><%= model_class.human_attribute_name(:closing) %>:</strong></dt>
  <dd><%= @deal.closing %></dd>
  <dt><strong><%= model_class.human_attribute_name(:admin) %>:</strong></dt>
  <dd><%= @deal.admin %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              deals_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_deal_path(@deal), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              deal_path(@deal),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>